const routing = require('express').Router()
const userController = require('../controllers/user')
const loginController = require('../controllers/login')
routing.route('/')
    .get(userController.getUsers)
routing.route('/login')
    .post(loginController.userLogin)
routing.route('/addSalary')
    .post(userController.addSalary)
routing.route('/editSalary')
    .post(userController.editSalary)
routing.route('/checkLoggedIn')
    .post(loginController.checkIfStillLogin)
routing.route('/logout')
    .post(loginController.userLogout)
routing.route('/register')
    .post(userController.setUser)
routing.route('/:id')
    .patch(userController.editUserData)
routing.route('/updatephoto/:id')
    .patch(userController.uploadProfile, userController.savePicture)
module.exports = routing